!$THEME = "C4_TriforkEhv"

!$ELEMENT_FONT_COLOR_PRIMARY ?= "#FFFFFF"
!$ELEMENT_FONT_COLOR_SECONDARY ?= "272C32" 

!$PERSON_FONT_COLOR ?= "#FF6600"
!$PERSON_BG_COLOR ?= "transparent" 
!$PERSON_BORDER_COLOR ?= "transparent" 
!$EXTERNAL_PERSON_FONT_COLOR ?= "#7B8696" 
!$EXTERNAL_PERSON_BG_COLOR ?= "transparent" 
!$EXTERNAL_PERSON_BORDER_COLOR ?= "transparent" 

!$SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY 
!$SYSTEM_BG_COLOR ?= "#DFAB86" 
!$SYSTEM_BORDER_COLOR ?= "#454D58" 
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY 
!$EXTERNAL_SYSTEM_BG_COLOR ?= "#F2D2BB" 
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= "#DFAB86" 

!$CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR_PRIMARY
!$CONTAINER_BG_COLOR ?= "#425663" 
!$CONTAINER_BORDER_COLOR ?= "#454D58" 
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY
!$EXTERNAL_CONTAINER_BG_COLOR ?= "#D5E3EB" 
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= "#97BDD3" 

!$COMPONENT_FONT_COLOR ?= "ELEMENT_FONT_COLOR_SECONDARY" 
!$COMPONENT_BG_COLOR ?= "#9EC3B1" 
!$COMPONENT_BORDER_COLOR ?= "#454D58" 
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $ELEMENT_FONT_COLOR_PRIMARY 
!$EXTERNAL_COMPONENT_BG_COLOR ?= "#CEDED6" 
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= "#9EC3B1" 


' <<<<<<<<<<<<< sequence diagram is styled via skinparam and style

' $BOUNDARY_BG_COLOR... have to be defined in theme itself that it can be used in styles,...
' (no default values which are defined in C4.puml) 
' If skinparams and styles are defined with concrete values no variables are required 
!$BOUNDARY_BG_COLOR ?= "#FBFCFD"
!$BOUNDARY_COLOR ?= "#272C32"
!$ARROW_COLOR ?= "#272C32"

' replace transparent with concrete background that it can be used as font color too
!if ($BOUNDARY_BG_COLOR == "transparent")
  !$SEQUENCE_BG_COLOR = white
!else
  !$SEQUENCE_BG_COLOR = $BOUNDARY_BG_COLOR
!endif

' "C4 styled" default is no foot boxes
hide footbox
' "C4 styled" default is that lifeline is arrow color
skinparam SequenceLifelineBorderColor $ARROW_COLOR

skinparam SequenceGroupBodyBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupFontColor $BOUNDARY_COLOR
skinparam SequenceGroupBackgroundColor $BOUNDARY_COLOR
skinparam SequenceGroupHeaderFontColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupBorderColor $BOUNDARY_COLOR

skinparam SequenceReferenceBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceReferenceFontColor $BOUNDARY_COLOR
skinparam SequenceReferenceHeaderBackgroundColor $BOUNDARY_COLOR
' VIA STYLE
' skinparam SequenceReferenceHeaderFontColor $SEQUENCE_BG_COLOR
<style>
referenceHeader {
  fontcolor $SEQUENCE_BG_COLOR
}
</style>
skinparam SequenceReferenceBorderColor $BOUNDARY_COLOR

skinparam SequenceDividerBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceDividerFontColor $BOUNDARY_COLOR
skinparam SequenceDividerBorderColor $BOUNDARY_COLOR

' VIA STYLE
' skinparam SequenceDelayFontColor green
<style>
sequenceDiagram {
  delay {
    FontColor $BOUNDARY_COLOR
  }
}
</style>

' <<<<<<<<<<<<< end sequence diagram
