!$THEME = "C4_TriforkEhv"

!$THEME_DARK_ORKA ?= "#272C32"
!$THEME_DARK_SHARK ?= "#373D46"
!$THEME_DARK_COD ?= "#454D58"
!$THEME_DARK_DOLPHIN ?= "#7B8696"
!$THEME_LIGHT_HIPPO ?= "#D0D9E2"
!$THEME_LIGHT_CLOUD ?= "#EFF3F7"
!$THEME_LIGHT_FOG ?= "#FBFCFD"
!$THEME_LIGHT_PURE ?= "#FFFFFF"
!$THEME_ACCENT_CORAL ?= "#FF3766"
!$THEME_ACCENT_SUN ?= "#FF6600"
!$THEME_ACCENT_LIME ?= "#44D7B6"
!$THEME_ACCENT_RAIN ?= "#9455FF"
!$THEME_BLUE ?= "#425663"
!$THEME_FADED_BLUE ?= "#D5E3EB"
!$THEME_DARK_FADED_BLUE ?= "#97BDD3"
!$THEME_DARK_FADED_ORANGE ?= "#DFAB86"
!$THEME_FADED_ORANGE ?= "#F2D2BB"
!$THEME_DARK_FADED_GREEN ?= "#9EC3B1"
!$THEME_FADED_GREEN ?= "#CEDED6"

!$ELEMENT_FONT_COLOR_PRIMARY ?= $THEME_LIGHT_PURE
!$ELEMENT_FONT_COLOR_SECONDARY ?= $THEME_DARK_ORKA 

!$PERSON_FONT_COLOR ?= $THEME_DARK_ORKA
!$PERSON_BG_COLOR ?= "transparent" 
!$PERSON_BORDER_COLOR ?= "transparent" 
!$EXTERNAL_PERSON_FONT_COLOR ?= $THEME_DARK_DOLPHIN 
!$EXTERNAL_PERSON_BG_COLOR ?= "transparent" 
!$EXTERNAL_PERSON_BORDER_COLOR ?= "transparent" 

!$SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY 
!$SYSTEM_BG_COLOR ?= $THEME_DARK_FADED_ORANGE 
!$SYSTEM_BORDER_COLOR ?= $THEME_ACCENT_SUN 
!$EXTERNAL_SYSTEM_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY 
!$EXTERNAL_SYSTEM_BG_COLOR ?= $THEME_FADED_ORANGE 
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $THEME_ACCENT_SUN 

!$CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR_PRIMARY
!$CONTAINER_BG_COLOR ?= $THEME_DARK_FADED_BLUE 
!$CONTAINER_BORDER_COLOR ?= $THEME_BLUE 
!$EXTERNAL_CONTAINER_FONT_COLOR ?= $ELEMENT_FONT_COLOR_SECONDARY
!$EXTERNAL_CONTAINER_BG_COLOR ?= $THEME_FADED_BLUE 
!$EXTERNAL_CONTAINER_BORDER_COLOR ?=  $THEME_BLUE

!$COMPONENT_FONT_COLOR ?= "ELEMENT_FONT_COLOR_SECONDARY" 
!$COMPONENT_BG_COLOR ?= $THEME_DARK_FADED_GREEN 
!$COMPONENT_BORDER_COLOR ?= $THEME_ACCENT_LIME 
!$EXTERNAL_COMPONENT_FONT_COLOR ?= $ELEMENT_FONT_COLOR_PRIMARY 
!$EXTERNAL_COMPONENT_BG_COLOR ?= $THEME_DARK_GREEN
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= $THEME_ACCENT_LIME 

!$NODE_FONT_COLOR ?= $THEME_DARK_ORKA
!$NODE_BG_COLOR ?= $THEME_LIGHT_PURE
!$NODE_BORDER_COLOR ?= $THEME_LIGHT_CLOUD

!$LEGEND_TITLE_COLOR ?= $THEME_DARK_ORKA
!$LEGEND_FONT_COLOR ?= $THEME_DARK_ORKA
!$LEGEND_BG_COLOR ?= "transparent"
!$LEGEND_BORDER_COLOR ?= "transparent"
!$LEGEND_DARK_COLOR ?= $THEME_DARK_SHARK
!$LEGEND_LIGHT_COLOR ?= $THEME_LIGHT_HIPPO
!$LEGEND_DETAILS_SMALL_SIZE ?= 10
!$LEGEND_DETAILS_NORMAL_SIZE ?= 14

!$ROUNDED_BOX_SIZE ?= 25
!$EIGHT_SIDED_SIZE ?= 18

' <<<<<<<<<<<<< sequence diagram is styled via skinparam and style

' $BOUNDARY_BG_COLOR... have to be defined in theme itself that it can be used in styles,...
' (no default values which are defined in C4.puml) 
' If skinparams and styles are defined with concrete values no variables are required 
!$BOUNDARY_BG_COLOR ?= $THEME_LIGHT_CLOUD
!$BOUNDARY_COLOR ?= $THEME_DARK_COD
!$ARROW_COLOR ?= $THEME_DARK_SHARK

!$ENTERPRISE_BOUNDARY_COLOR ?= $BOUNDARY_COLOR
!$ENTERPRISE_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$ENTERPRISE_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$SYSTEM_BOUNDARY_COLOR ?= $BOUNDARY_COLOR
!$SYSTEM_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$SYSTEM_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

!$CONTAINER_BOUNDARY_COLOR ?= $BOUNDARY_COLOR
!$CONTAINER_BOUNDARY_BG_COLOR ?= $BOUNDARY_BG_COLOR
!$CONTAINER_BOUNDARY_BORDER_STYLE ?= $BOUNDARY_BORDER_STYLE

' replace transparent with concrete background that it can be used as font color too
!if ($BOUNDARY_BG_COLOR == "transparent")
  !$SEQUENCE_BG_COLOR = white
!else
  !$SEQUENCE_BG_COLOR = $BOUNDARY_BG_COLOR
!endif

'skinparam defaultFontName "Liberation Mono"
skinparam defaultFontName "DejaVu Sans Mono"

' "C4 styled" default is no foot boxes
hide footbox
' "C4 styled" default is that lifeline is arrow color
skinparam SequenceLifelineBorderColor $ARROW_COLOR

skinparam SequenceGroupBodyBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupFontColor $BOUNDARY_COLOR
skinparam SequenceGroupBackgroundColor $BOUNDARY_COLOR
skinparam SequenceGroupHeaderFontColor $SEQUENCE_BG_COLOR
skinparam SequenceGroupBorderColor $BOUNDARY_COLOR

skinparam SequenceReferenceBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceReferenceFontColor $BOUNDARY_COLOR
skinparam SequenceReferenceHeaderBackgroundColor $BOUNDARY_COLOR
' VIA STYLE
' skinparam SequenceReferenceHeaderFontColor $SEQUENCE_BG_COLOR
<style>
referenceHeader {
  fontcolor $SEQUENCE_BG_COLOR
}
</style>
skinparam SequenceReferenceBorderColor $BOUNDARY_COLOR

skinparam SequenceDividerBackgroundColor $SEQUENCE_BG_COLOR
skinparam SequenceDividerFontColor $BOUNDARY_COLOR
skinparam SequenceDividerBorderColor $BOUNDARY_COLOR

' VIA STYLE
' skinparam SequenceDelayFontColor green
<style>
sequenceDiagram {
  delay {
    FontColor $BOUNDARY_COLOR
  }
}
</style>

' <<<<<<<<<<<<< end sequence diagram
